--liquibase formatted sql
--changeset matsyuk.yum:1 dbms=oracle

CREATE OR REPLACE VIEW Z_VW_USER_LIST AS
(
select
u.usr_udf_is_deleted, u.usr_udf_ext_status, u."USR_KEY",u."ACT_KEY",u."USR_LAST_NAME",u."USR_FIRST_NAME",u."USR_MIDDLE_NAME",
u."USR_DISPLAY_NAME",u."USR_MANAGER",u."USR_TYPE",u."USR_LOCATION",u."USR_FSS",
upper(u."USR_DISPLAY_NAME") as USR_DISPLAY_NAME_upper,
u."USR_TODO",u."USR_PASSWORD",u."USR_DISABLED",u."USR_PWD_CANT_CHANGE",
u."USR_PWD_MUST_CHANGE",u."USR_PWD_NEVER_EXPIRES",u."USR_UPDATE_AD",
u."USR_STATUS",u."USR_EMP_TYPE",u."USR_LOGIN",u."USR_DISABLED_BY_PARENT"
,u."USR_PWD_EXPIRE_DATE",u."USR_PWD_WARN_DATE",u."USR_MANAGER_KEY",u."USR_POLICY_UPDATE",
u."USR_PWD_WARNED",u."USR_PWD_EXPIRED",u."USR_START_DATE",u."USR_END_DATE",
u."USR_PROVISIONING_DATE",u."USR_DEPROVISIONING_DATE",u."USR_PROVISIONED_DATE",u."USR_DEPROVISIONED_DATE",
(case
when usr_emp_type='CWK' then u.usr_udf_cwk_email else u.usr_email end )
as USR_EMAIL

,u."USR_LOCKED",u."USR_LOGIN_ATTEMPTS_CTR",u."USR_PWD_RESET_ATTEMPTS_CTR",u."USR_CHANGE_PWD_AT_NEXT_LOGON",
u."USR_PWD_MIN_AGE_DATE",u."USR_TIMEZONE",u."USR_LOCALE",u."USR_LOCKED_ON",u."USR_MANUALLY_LOCKED",
u."USR_AUTOMATICALLY_DELETE_ON",u."USR_FULL_NAME",u."USR_COUNTRY",u."USR_DEPT_NO",u."USR_DESCRIPTION",
u."USR_COMMON_NAME",u."USR_EMP_NO",u."USR_FAX",u."USR_GEN_QUALIFIER",u."USR_HIRE_DATE",u."USR_HOME_PHONE",
u."USR_LOCALITY_NAME",u."USR_MOBILE",u."USR_PAGER",u."USR_HOME_POSTAL_ADDRESS",u."USR_POSTAL_ADDRESS",
u."USR_POSTAL_CODE",u."USR_PO_BOX",u."USR_STATE",u."USR_STREET",u."USR_TELEPHONE_NUMBER",u."USR_TITLE",
u."USR_INITIALS",u."USR_PWD_GENERATED",u."USR_LDAP_ORGANIZATION",u."USR_LDAP_ORGANIZATION_UNIT",
u."USR_LDAP_GUID",u."USR_LDAP_DN",u."USR_ACCESSIBILITY_MODE",u."USR_COLOR_CONTRAST",
u."USR_FONT_SIZE",u."USR_NUMBER_FORMAT",u."USR_CURRENCY",u."USR_DATE_FORMAT",
u."USR_TIME_FORMAT",u."USR_EMBEDDED_HELP",u."USR_LANGUAGE",u."USR_TERRITORY",
u."USR_NAME_PREFERRED_LANG",u."USR_CN_GENERATED",u."USR_SUMMARY_RISK",u."USR_HAS_HIGH_RISK_ROLE",
u."USR_HAS_HIGH_RISK_RESOURCE",u."USR_HAS_HIGH_RISK_ENTITLEMENT",u."USR_HAS_HIGH_RISK_PROV_METH",
u."USR_HAS_HIGH_RISK_OPEN_SOD",u."USR_HAS_HIGH_RISK_LAST_CERT",u."USR_ROLE_SUMMARY_RISK",
u."USR_ACCOUNT_SUMMARY_RISK",u."USR_ENTITLEMENT_SUMMARY_RISK",u."USR_JOB_CODE",u."USR_OFFICE_NAME",
u."USR_RISK_UPDATE_DATE",u."USR_DATA_LEVEL",u."USR_CREATED",u."USR_CREATE",u."USR_CREATEBY",
u."USR_UPDATE",u."USR_UPDATEBY",u."USR_NOTE",u."USR_ROWVER",u."USR_UDF_CONF_AGREEMENT",
u."USR_UDF_BIRTH_DATE",u."USR_UDF_OFFICE",u."USR_UDF_NOMENCLATURE",u."USR_UDF_PHONE_EXTENSION",
u."USR_UDF_UNIQUE_ID",u."USR_UDF_CITY",u."USR_UDF_OBGUID",u."USR_UDF_REAL_CITY",u."USR_UDF_KEEP_REAL_CITY",
(case
when usr_udf_department_name is not null then usr_udf_department_name
  else nvl(act.org_udf_department_name, act.act_name) end
 )
as act_name,
(case
when usr_emp_type='Contractor' then '���������'
when u.usr_title is null then u.usr_udf_title_name
  else nvl(z_titles.title_name, u.usr_title)
  end) as usr_title_hr,
u.usr_udf_codeword
 from usr u
 inner join act on u.act_key=act.act_key
           left join z_titles on u.usr_title=z_titles.title_id_full
);



--rollback DROP VIEW Z_VW_USER_LIST;