--liquibase formatted sql
--changeset matsyuk.yum:1 dbms=oracle

ALTER TABLE GPN_OIM.Z_PROCESS_STEP ADD (
  MODIFIED_DATE   TIMESTAMP(6), 
  APPROVED_BY     NUMBER,
  STEP_STATE      VARCHAR2(50 CHAR),
  STEP_OUTCOME    VARCHAR2(50 CHAR), 
  ORDER_NUM       NUMBER
);

--rollback ALTER TABLE GPN_OIM.Z_PROCESS_STEP DROP COLUMN MODIFIED_DATE;
--rollback ALTER TABLE GPN_OIM.Z_PROCESS_STEP DROP COLUMN APPROVED_BY;
--rollback ALTER TABLE GPN_OIM.Z_PROCESS_STEP DROP COLUMN STEP_STATE;
--rollback ALTER TABLE GPN_OIM.Z_PROCESS_STEP DROP COLUMN STEP_OUTCOME;
--rollback ALTER TABLE GPN_OIM.Z_PROCESS_STEP DROP COLUMN ORDER_NUM;