--liquibase formatted sql
--changeset matsyuk.yum:1 dbms=oracle

TRUNCATE TABLE GPN_OIM.Z_WIDGET_SETS_WIDGETS;

INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'create_requests', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'create_requests', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_users_create', 'EDIT_MAIN_INFO', TO_TIMESTAMP('2019-02-21 10:28:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_users_edit', 'EDIT_MAIN_INFO', TO_TIMESTAMP('2019-02-21 10:28:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_organizations_add', null, TO_TIMESTAMP('2019-02-21 17:20:17.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_organizations_edit', null, TO_TIMESTAMP('2019-02-21 17:20:17.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_add_resource', null, TO_TIMESTAMP('2019-07-18 12:38:32.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_edit_resource', null, TO_TIMESTAMP('2019-07-18 12:38:32.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_add_account_for_system', null, TO_TIMESTAMP('2019-08-06 12:00:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_change_access_to_spec_account', null, TO_TIMESTAMP('2019-08-08 09:53:58.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_revoke_access_to_spec_account', null, TO_TIMESTAMP('2019-08-08 09:53:58.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_change_date_for_access_spec_account', null, TO_TIMESTAMP('2019-08-08 09:53:58.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_revoke_access_for_spec_account', null, TO_TIMESTAMP('2019-08-08 09:53:58.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'catalog_users_show', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'search', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'catalog_users', 'EDIT_SUBORDINATES_USERS', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'catalogs', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'request_details', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'request_add_resource', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'catalog_resources', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'test_page', null, TO_TIMESTAMP('2019-08-21 09:21:21.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'global', 'REQUEST_SKIP_APPROVALS', TO_TIMESTAMP('2019-08-26 10:14:34.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'catalog_resources_edit', null, TO_TIMESTAMP('2019-08-24 17:37:33.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_add_entitlement_conf_data', null, TO_TIMESTAMP('2019-08-06 10:04:46.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_edit_spec_account', null, TO_TIMESTAMP('2019-08-07 14:30:46.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_temp_spec_acc', null, TO_TIMESTAMP('2019-07-26 10:04:26.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'test_widget_with_graph', null, TO_TIMESTAMP('2019-08-21 12:03:54.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'test_widget_with_buttons', null, TO_TIMESTAMP('2019-08-21 12:04:59.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'test_widget_with_graph_2', null, TO_TIMESTAMP('2019-08-21 12:44:45.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'catalog_organizations', null, TO_TIMESTAMP('2019-08-22 15:58:22.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'requests', null, TO_TIMESTAMP('2019-08-22 16:01:04.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'requests_history', null, TO_TIMESTAMP('2019-08-22 16:03:47.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'my_approvals', null, TO_TIMESTAMP('2019-08-22 16:03:47.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_users_show', ' HISTORY_CHANGES,
 PERSONAL_ENTITLEMENTS_LINK_ACCOUNT,
 PERSONAL_ENTITLEMENTS_LINK_EMPLOYMENT,
 SPECIAL_ENTITLEMENTS_LINK_ACCOUNT,
 SPECIAL_ENTITLEMENTS_LINK_EMPLOYMENT,
 PERSONAL_ACCOUNT_RULES_RETRY,
 SPECIAL_ACCOUNT_RULES_RETRY,
 PERSONAL_ACCOUNTS_LINK_ACCOUNT,
 PERSONAL_ACCOUNTS_UNLINK_ACCOUNT,
 PERSONAL_ACCOUNTS_SYNCHRONIZATION_FROM_SYSTEM,
 PERSONAL_ACCOUNTS_UPDATE_ATTRS,
 PERSONAL_ACCOUNTS_HISTORY,
 PERSONAL_ACCOUNTS_LOCK_BY_ALL_INCIDENTS,
 SPECIAL_ACCOUNTS_LINK_ACCOUNT,
 SPECIAL_ACCOUNTS_UNLINK_ACCOUNT,
 SPECIAL_ACCOUNTS_SYNCHRONIZATION_FROM_SYSTEM,
 SPECIAL_ACCOUNTS_UPDATE_ATTRS,
 SPECIAL_ACCOUNTS_HISTORY,
 SPECIAL_ACCOUNTS_LOCK_BY_ALL_INCIDENTS,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_GRANT,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_REVOKE,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_CHANGE_DATE,
 EDIT_BASIC_LAST_NAME,
 EDIT_BASIC_FIRST_NAME,
 EDIT_BASIC_MIDDLE_NAME,
 EDIT_BASIC_BIRTH_DATE,
 EDIT_BASIC_EMAIL,
 EDIT_TIMOUT_BLOCK,
 EDIT_TIMOUT_REVOKE,
 EDIT_CONTACT_INNER_PHONE,
 EDIT_CONTACT_PHONE,
 EDIT_CONTACT_MOBILE_PHONE,
 EDIT_CONTACT_EMAIL,
 EDIT_LOCATION_REAL_CITY,
 EDIT_LOCATION_REAL_ADDRESS,
 EDIT_EMPLOYMENT_ADD,
 KDP_TAB_DISPLAY', TO_TIMESTAMP('2019-02-21 13:10:50.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_resources_edit', 'EDIT_RESOURCE', TO_TIMESTAMP('2019-02-27 14:15:47.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_resources_add', null, TO_TIMESTAMP('2019-02-27 14:15:47.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'admin', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('BASE_SET', 'access_request', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('BASE_SET', 'sent_requests', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'access_request', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'change_access_dates', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'sent_requests', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'root', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'settings', 'USER_SETTINGS', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'access_is_denied_page', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'widget_store', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('SUPPORT_SET', 'access_request', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('SUPPORT_SET', 'change_access_dates', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('SUPPORT_SET', 'sent_requests', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('SUPPORT_SET', 'requests_history', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('MANAGER_SET', 'access_request', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('MANAGER_SET', 'change_access_dates', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('MANAGER_SET', 'set_replacement', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('MANAGER_SET', 'my_approvals', 'APPROVE_REQUEST, REJECT_REQUEST, FORWARD_REQUEST', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('MANAGER_SET', 'sent_requests', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('MANAGER_SET', 'requests_history', 'RETRY_REQUEST', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'access_request', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'change_access_dates', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'set_replacement', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'create_external_user', 'HISTORY_CHANGES,
 PERSONAL_ENTITLEMENTS_LINK_ACCOUNT,
 PERSONAL_ENTITLEMENTS_LINK_EMPLOYMENT,
 SPECIAL_ENTITLEMENTS_LINK_ACCOUNT,
 SPECIAL_ENTITLEMENTS_LINK_EMPLOYMENT,
 PERSONAL_ACCOUNT_RULES_RETRY,
 SPECIAL_ACCOUNT_RULES_RETRY,
 PERSONAL_ACCOUNTS_LINK_ACCOUNT,
 PERSONAL_ACCOUNTS_UNLINK_ACCOUNT,
 PERSONAL_ACCOUNTS_SYNCHRONIZATION_FROM_SYSTEM,
 PERSONAL_ACCOUNTS_UPDATE_ATTRS,
 PERSONAL_ACCOUNTS_HISTORY,
 PERSONAL_ACCOUNTS_LOCK_BY_ALL_INCIDENTS,
 SPECIAL_ACCOUNTS_LINK_ACCOUNT,
 SPECIAL_ACCOUNTS_UNLINK_ACCOUNT,
 SPECIAL_ACCOUNTS_SYNCHRONIZATION_FROM_SYSTEM,
 SPECIAL_ACCOUNTS_UPDATE_ATTRS,
 SPECIAL_ACCOUNTS_HISTORY,
 SPECIAL_ACCOUNTS_LOCK_BY_ALL_INCIDENTS,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_GRANT,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_REVOKE,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_CHANGE_DATE,
 EDIT_BASIC_LAST_NAME,
 EDIT_BASIC_FIRST_NAME,
 EDIT_BASIC_MIDDLE_NAME,
 EDIT_BASIC_BIRTH_DATE,
 EDIT_BASIC_EMAIL,
 EDIT_TIMOUT_BLOCK,
 EDIT_TIMOUT_REVOKE,
 EDIT_CONTACT_INNER_PHONE,
 EDIT_CONTACT_PHONE,
 EDIT_CONTACT_MOBILE_PHONE,
 EDIT_CONTACT_EMAIL,
 EDIT_LOCATION_REAL_CITY,
 EDIT_LOCATION_REAL_ADDRESS,
 EDIT_EMPLOYMENT_ADD,
 KDP_TAB_DISPLAY', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'my_approvals', 'APPROVE_REQUEST, REJECT_REQUEST, FORWARD_REQUEST', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'sent_requests', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'requests_history', 'RETRY_REQUEST', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'root', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'access_is_denied_page', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'settings', 'ADMIN_SETTINGS', TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'widget_store', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'info', null, TO_TIMESTAMP('2019-01-29 15:12:43.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'admin_tasks', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'audit', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'binding_service_sap_accounts', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'binding_tender_sap_accounts', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'change_acounts_accesses', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'companies', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'diagnostics', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'information_systems', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'load', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'organizational_structure', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'reconciliation_events', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'reports', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'roles', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_companies', null, TO_TIMESTAMP('2019-03-01 16:08:45.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_company_edit', null, TO_TIMESTAMP('2019-03-01 16:08:45.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'access_revocation', null, TO_TIMESTAMP('2019-04-02 10:40:52.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'access_revocation', null, TO_TIMESTAMP('2019-08-24 16:40:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'request_edit_resource', null, TO_TIMESTAMP('2019-08-24 16:41:18.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'request_add_entitlement_conf_data', null, TO_TIMESTAMP('2019-08-24 16:44:11.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_access_based_on_agreed_paper_request', null, TO_TIMESTAMP('2019-08-24 16:59:22.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_organizations', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_resources', 'ADD_RESOURCE', null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalog_users', 'ADD_USER, EDIT_ALL_USERS', null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'catalogs', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'edit_profile', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'incoming_requests', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'main', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'profile', ' HISTORY_CHANGES,
 PERSONAL_ENTITLEMENTS_LINK_ACCOUNT,
 PERSONAL_ENTITLEMENTS_LINK_EMPLOYMENT,
 SPECIAL_ENTITLEMENTS_LINK_ACCOUNT,
 SPECIAL_ENTITLEMENTS_LINK_EMPLOYMENT,
 PERSONAL_ACCOUNT_RULES_RETRY,
 SPECIAL_ACCOUNT_RULES_RETRY,
 PERSONAL_ACCOUNTS_LINK_ACCOUNT,
 PERSONAL_ACCOUNTS_UNLINK_ACCOUNT,
 PERSONAL_ACCOUNTS_SYNCHRONIZATION_FROM_SYSTEM,
 PERSONAL_ACCOUNTS_UPDATE_ATTRS,
 PERSONAL_ACCOUNTS_HISTORY,
 PERSONAL_ACCOUNTS_LOCK_BY_ALL_INCIDENTS,
 SPECIAL_ACCOUNTS_LINK_ACCOUNT,
 SPECIAL_ACCOUNTS_UNLINK_ACCOUNT,
 SPECIAL_ACCOUNTS_SYNCHRONIZATION_FROM_SYSTEM,
 SPECIAL_ACCOUNTS_UPDATE_ATTRS,
 SPECIAL_ACCOUNTS_HISTORY,
 SPECIAL_ACCOUNTS_LOCK_BY_ALL_INCIDENTS,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_GRANT,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_REVOKE,
 ENTITLEMENT_TO_SPECIAL_ACCOUNT_REPEAT_CHANGE_DATE,
 EDIT_BASIC_LAST_NAME,
 EDIT_BASIC_FIRST_NAME,
 EDIT_BASIC_MIDDLE_NAME,
 EDIT_BASIC_BIRTH_DATE,
 EDIT_BASIC_EMAIL,
 EDIT_TIMOUT_BLOCK,
 EDIT_TIMOUT_REVOKE,
 EDIT_CONTACT_INNER_PHONE,
 EDIT_CONTACT_PHONE,
 EDIT_CONTACT_MOBILE_PHONE,
 EDIT_CONTACT_EMAIL,
 EDIT_LOCATION_REAL_CITY,
 EDIT_LOCATION_REAL_ADDRESS,
 EDIT_EMPLOYMENT_ADD,
 KDP_TAB_DISPLAY', null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_details', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'search', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'requests', null, null, null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'profile', null, TO_TIMESTAMP('2019-04-01 18:37:30.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'edit_profile', null, TO_TIMESTAMP('2019-04-01 18:37:49.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'request_add_entitlement_spec_acc', null, TO_TIMESTAMP('2019-07-30 14:43:05.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('USER_SET', 'catalog_users_edit', 'EDIT_MAIN_INFO', TO_TIMESTAMP('2019-04-01 18:50:42.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);
INSERT INTO GPN_OIM.Z_WIDGET_SETS_WIDGETS (WIDGET_SET_CODE, WIDGET_CODE, FUNCTION_CODE_LIST, CREATE_DATE, UPDATE_DATE) VALUES ('ADMIN_SET', 'add_entitlement_to_spec_account', null, TO_TIMESTAMP('2019-07-30 14:41:51.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null);

COMMIT;

--rollback TRUNCATE TABLE GPN_OIM.Z_WIDGET_SETS_WIDGETS;