--liquibase formatted sql
--changeset matsyuk.yum:1 dbms=oracle

CREATE TABLE REQUEST_ITEM_AND_CONF_ITEM_REF
(
	ID NUMBER NOT NULL
	, REQUEST_ITEM_ID NUMBER NOT NULL
	, CONF_ITEM_ID NUMBER NOT NULL
	
	, CONSTRAINT ID_PK PRIMARY KEY(ID)
);

COMMENT ON TABLE REQUEST_ITEM_AND_CONF_ITEM_REF IS '';
COMMENT ON COLUMN REQUEST_ITEM_AND_CONF_ITEM_REF.ID IS 'id ';
COMMENT ON COLUMN REQUEST_ITEM_AND_CONF_ITEM_REF.REQUEST_ITEM_ID IS '';
COMMENT ON COLUMN REQUEST_ITEM_AND_CONF_ITEM_REF.CONF_ITEM_ID IS '';

--rollback DROP TABLE REQUEST_ITEM_AND_CONF_ITEM_REF;