--liquibase formatted sql
--changeset matsyuk.yum:1 dbms=oracle

CREATE INDEX GPN_OIM.Z_PROCESS_STEP_ATTRS_N1 ON GPN_OIM.Z_PROCESS_STEP_ATTRS
(STEP_ID, ATTRNAME)
LOGGING
TABLESPACE GPN_OIM;

--rollback DROP INDEX GPN_OIM.Z_PROCESS_STEP_ATTRS_N1;